src/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SiswaController;
use App\Http\Controllers\KelasController;
use App\Http\Controllers\GuruController;
use App\Http\Controllers\BarangController;
use App\Http\Controllers\BarangTetapController;
use App\Http\Controllers\PeminjamanController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UserProfileController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::middleware(['auth','admin'])->group(function () {
    //
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
    
    Route::get('/admin/siswa', [SiswaController::class, 'index'])->name('admin.siswa');
    Route::post('/admin/siswa', [SiswaController::class, 'store'])->name('admin.siswa.store');
    Route::patch('/admin/siswa/{id}/update', [SiswaController::class, 'update'])->name('admin.siswa.update');
    Route::get('/admin/siswa/kelas/{id}', [SiswaController::class, 'kelas'])->name('admin.siswa.kelas');
    Route::get('/admin/siswa/{id}/edit', [SiswaController::class, 'edit'])->name('admin.siswa.edit');
    Route::delete('/admin/siswa/{id}/destroy', [SiswaController::class, 'destroy'])->name('admin.siswa.destroy');
    
    
    Route::get('/admin/kelas', [KelasController::class, 'index'])->name('admin.kelas');
    Route::post('/admin/kelas', [KelasController::class, 'store'])->name('admin.kelas.store');
    Route::delete('/admin/kelas/{id}', [KelasController::class, 'destroy'])->name('admin.kelas.destroy');
    
    
    Route::get('/admin/guru', [GuruController::class, 'index'])->name('admin.guru');
    Route::get('/admin/guru/{id}/edit', [GuruController::class, 'edit'])->name('admin.guru.edit');
    Route::post('/admin/guru', [GuruController::class, 'store'])->name('admin.guru.store');
    Route::delete('/admin/guru/{id}/delete', [GuruController::class, 'destroy'])->name('admin.guru.destroy');
    Route::patch('/admin/guru/{id}/update', [GuruController::class, 'update'])->name('admin.guru.update');
    
    
    Route::get('/admin/barang', [BarangController::class, 'index'])->name('admin.barang');
    Route::post('/admin/barang', [BarangController::class, 'store'])->name('admin.barang.store');
    Route::get('/admin/barang/{id}/edit', [BarangController::class, 'edit'])->name('admin.barang.edit');
    Route::patch('/admin/barang/{id}/update', [BarangController::class, 'update'])->name('admin.barang.update');
    Route::delete('/admin/barang/{id}/delete', [BarangController::class, 'destroy'])->name('admin.barang.destroy');
    Route::get('/admin/barang/print', [BarangController::class, 'print'])->name('admin.barang.print');


    // barang tetap

    Route::get('/admin/barangtetap', [BarangTetapController::class, 'index'])->name('admin.barangtetap');
    Route::post('/admin/barangtetap', [BarangTetapController::class, 'store'])->name('admin.barangtetap.store');
    Route::get('/admin/barangtetap/{id}/edit', [BarangTetapController::class, 'edit'])->name('admin.barangtetap.edit');
    Route::patch('/admin/barangtetap/{id}/update', [BarangTetapController::class, 'update'])->name('admin.barangtetap.update');
    Route::delete('/admin/barangtetap/{id}/delete', [BarangTetapController::class, 'destroy'])->name('admin.barangtetap.destroy');
    Route::get('/admin/barangtetap/print', [BarangTetapController::class, 'print'])->name('admin.barangtetap.print');
    

    Route::get('/admin/peminjaman', [PeminjamanController::class, 'index'])->name('admin.peminjaman');
    Route::patch('/admin/peminjaman/{id}/update', [PeminjamanController::class, 'updateKeterangan'])->name('user.peminjaman.updateKeterangan');
    Route::get('/admin/peminjaman/export', [PeminjamanController::class, 'exportPDF'])->name('admin.peminjaman.exportpdf');
    
});



// ROUTE FOR SISWA / GURU
Route::middleware(['auth','users'])->group(function () {
    //
    Route::get('/user', [PeminjamanController::class, 'userIndex'])->name('user.dashboard');
    Route::get('/user/peminjaman', [PeminjamanController::class, 'userIndex'])->name('user.peminjaman');
    Route::post('/user/peminjaman', [PeminjamanController::class, 'store'])->name('user.peminjaman.store');
    Route::patch('/user/peminjaman/{id}/update', [PeminjamanController::class, 'updateKeterangan'])->name('peminjaman.updateKeterangan');
    Route::get('/user/myprofile', [UserProfileController::class, 'index'])->name('user.myprofile');
    Route::post('/user/password/update', [UserProfileController::class, 'changePassword'])->name('user.passchange');
});



require __DIR__.'/auth.php';

src/app/Models/Peminjaman.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
class Peminjaman extends Model
{
    use HasFactory;
    use SoftDeletes;
    protected $table = 'peminjaman';

    protected $fillable = [
        'peminjam_id','status','barang_id','keterangan'
    ];
}

src/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role',
        'no_induk',
        'nip',
        
    ];

    // public function guru($id)
    // {
    //     $guru = Guru::where('nip', $id)->first();
    //     return $guru;
    // }

    // public function siswa($id)
    // {
    //     $siswa = Siswa::where('no_induk', $id)->first();
    //     return $siswa;
    // }

    public function guru()
    {
        # code...
        return $this->belongsTo(Guru::class, 'nip', 'nip');
    }
    public function siswa()
    {
        # code...
        return $this->belongsTo(Siswa::class, 'no_induk', 'no_induk');
    }
    public function isUsers()
    {
        # code...
        if($this->role === 'Siswa' || $this->role === 'Guru' || $this->role === 'Guest')
        { 
            return true; 
        } 
        else 
        { 
            return false; 
        }
    }
    public function isAdmin()
    {
        # code...
        if($this->role === 'Admin')
        { 
            return true; 
        } 
        else 
        { 
            return false; 
        }
    }

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

src/app/Http/Controllers/PeminjamanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Kelas;
use App\Models\Siswa;
use App\Models\Guru;
use App\Models\User;
use App\Models\Barang;
use App\Models\BarangTetap;
use App\Models\Peminjaman;
use Barryvdh\DomPDF\Facade\Pdf;
use App;
use Auth;

class PeminjamanController extends Controller
{
    //
    public function index(Request $request)
    {
        # code...
        if ($request->date) {
            # code...
            $date = explode(" to ", $request->date);
            $peminjamansiswa = Peminjaman::select('barang.nama as nama_barang','barang.nomor','peminjaman.*', 'siswa.nama as nama_siswa')
            ->whereNull('siswa.deleted_at')
            ->where('peminjaman.status', 'Siswa')
            ->whereBetween('peminjaman.created_at', [$date[0], $date[1]])
            ->join('siswa', 'siswa.id', 'peminjaman.peminjam_id')
            ->join('barang', 'barang.id', 'peminjaman.barang_id')->get();
            $peminjamanguru = Peminjaman::select('barang.nama as nama_barang','barang.nomor','peminjaman.*', 'guru.nama as nama_guru')
            ->whereNull('guru.deleted_at')
            ->where('peminjaman.status', 'Guru')
            ->whereBetween('peminjaman.created_at', [$date[0], $date[1]])
            ->join('guru', 'guru.id', 'peminjaman.peminjam_id')
            ->join('barang', 'barang.id', 'peminjaman.barang_id')->get();

            return view('admin.peminjaman.index', compact('peminjamanguru', 'peminjamansiswa', 'date'));
        }else{
            $peminjamansiswa = Peminjaman::select('barang.nama as nama_barang','barang.nomor','peminjaman.*', 'siswa.nama as nama_siswa')
            ->whereNull('siswa.deleted_at')
            ->where('peminjaman.status', 'Siswa')
            ->join('siswa', 'siswa.id', 'peminjaman.peminjam_id')
            ->join('barang', 'barang.id', 'peminjaman.barang_id')->get();
            $peminjamanguru = Peminjaman::select('barang.nama as nama_barang','barang.nomor','peminjaman.*', 'guru.nama as nama_guru')
            ->whereNull('guru.deleted_at')
            ->where('peminjaman.status', 'Guru')
            ->join('guru', 'guru.id', 'peminjaman.peminjam_id')
            ->join('barang', 'barang.id', 'peminjaman.barang_id')->get();
            return view('admin.peminjaman.index', compact('peminjamanguru', 'peminjamansiswa'));
        }
        
    }
    public function userIndex()
    {
        # code...
        $barang = Barang::whereNotIn('id', function ($query){
            $query->select('barang_id')->from('peminjaman')
            ->where('keterangan', 'Barang sedang dipinjam');
        })->get();
        $user = Auth::user();
        // return $peminjaman;
        if ($user->role == 'Siswa') {
            # code...
            $profile = Siswa::where('no_induk', $user->no_induk)->first();

            $peminjaman = Peminjaman::select('barang.nama as nama_barang','barang.nomor','peminjaman.*')
            ->where('peminjaman.peminjam_id', $profile->id)
            ->where('peminjaman.status', 'Siswa')

            ->join('barang', 'barang.id', 'peminjaman.barang_id')->get();

            return view('user.peminjaman.index', compact('barang','profile','peminjaman'));
        }elseif ($user->role == 'Guru') {
            # code...
            $profile = Guru::where('nip', $user->nip)->first();
            
            $peminjaman = Peminjaman::select('barang.nama as nama_barang','barang.nomor','peminjaman.*')
            ->where('peminjaman.peminjam_id', $profile->id)
            ->where('peminjaman.status', 'Guru')

            ->join('barang', 'barang.id', 'peminjaman.barang_id')->get();
            return view('user.peminjaman.index', compact('barang','profile','peminjaman'));
        }else{
            $peminjamansiswa = Peminjaman::select('barang.nama as nama_barang','barang.nomor','peminjaman.*', 'siswa.nama as nama_siswa')
            ->where('peminjaman.status', 'Siswa')
            ->whereNull('siswa.deleted_at')
            ->join('siswa', 'siswa.id', 'peminjaman.peminjam_id')
            ->join('barang', 'barang.id', 'peminjaman.barang_id')->get();
            $peminjamanguru = Peminjaman::select('barang.nama as nama_barang','barang.nomor','peminjaman.*', 'guru.nama as nama_guru')
            ->where('peminjaman.status', 'Guru')
            ->whereNull('guru.deleted_at')
            ->join('guru', 'guru.id', 'peminjaman.peminjam_id')
            ->join('barang', 'barang.id', 'peminjaman.barang_id')->get();

            $barang = Barang::all();
            $barangtetap = BarangTetap::all();
            return view('user.peminjaman.guest', compact('peminjamanguru', 'peminjamansiswa', 'barang', 'barangtetap'));

        }
    }
    public function store(Request $request){
        Peminjaman::create([
            'peminjam_id' => $request->peminjam_id,
            'status' => $request->status,
            'barang_id' => $request->barang_id,
            'keterangan' => 'Barang sedang dipinjam'
        ]);
        return redirect()->back()->with('success', 'Data pengajuan peminjaman barang berhasil!');

    }
    public function updateKeterangan(Request $request, $id)
    {
        # code...
        // return $request;
        $peminjaman = Peminjaman::findorfail($id);
        $peminjaman->update([
            'keterangan' => $request->data
        ]);
        return redirect()->back()->with('success', 'Data pengajuan peminjaman barang diperbaruhi!');

    }
    public function exportPDF(Request $request)
    {
        # code...
        // return "hehe";
        
        if ($request->date) {
            # code...
            $date = explode(" to ", $request->date);
            $peminjamansiswa = Peminjaman::select('barang.nama as nama_barang','barang.nomor','peminjaman.*', 'siswa.nama as nama_siswa')
            ->whereNull('siswa.deleted_at')
            ->whereBetween('peminjaman.created_at', [$date[0], $date[1]])
            ->join('siswa', 'siswa.id', 'peminjaman.peminjam_id')
            ->join('barang', 'barang.id', 'peminjaman.barang_id')->get();
            $peminjamanguru = Peminjaman::select('barang.nama as nama_barang','barang.nomor','peminjaman.*', 'guru.nama as nama_guru')
            ->whereNull('guru.deleted_at')
            ->whereBetween('peminjaman.created_at', [$date[0], $date[1]])
            ->join('guru', 'guru.id', 'peminjaman.peminjam_id')
            ->join('barang', 'barang.id', 'peminjaman.barang_id')->get();

            // $pdf = PDF::loadView('admin.peminjaman.export', $peminjamanguru);
            $pdfview = view('admin.peminjaman.export', compact('peminjamanguru', 'peminjamansiswa', 'date'));
            $pdf = App::make('dompdf.wrapper');
$invPDF = $pdf->loadHTML($pdfview);
return $pdf->download('invoice.pdf');
        }else{
            $peminjamansiswa = Peminjaman::select('barang.nama as nama_barang','barang.nomor','peminjaman.*', 'siswa.nama as nama_siswa')
            ->whereNull('siswa.deleted_at')
            ->join('siswa', 'siswa.id', 'peminjaman.peminjam_id')
            ->join('barang', 'barang.id', 'peminjaman.barang_id')->get();
            $peminjamanguru = Peminjaman::select('barang.nama as nama_barang','barang.nomor','peminjaman.*', 'guru.nama as nama_guru')
            ->whereNull('guru.deleted_at')
            ->join('guru', 'guru.id', 'peminjaman.peminjam_id')
            ->join('barang', 'barang.id', 'peminjaman.barang_id')->get();

            $pdfview = view('admin.peminjaman.export', compact('peminjamanguru', 'peminjamansiswa'));
            $pdf = App::make('dompdf.wrapper');
$invPDF = $pdf->loadHTML($pdfview);
return $pdf->download('invoice.pdf');
        }
    }
}

src/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class UserController extends Controller
{
    //

    public function myprofile()
    {
        # code...
        return view('user.profile.index');
    }
}

src/app/View/Components/UserLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class UserLayout extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('layouts.user');

    }
}

src/resources/views/user/peminjaman/guest.blade.php
<x-user-layout>
    <x-slot name="header">
        {{ __('Dashboard') }}
    </x-slot>
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    
                </h3>
            </div>
            <div class="card-body">
                <ul class="nav nav-tabs justify-content-center" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" id="siswa-tab-center" data-bs-toggle="tab" href="#siswa-center"
                            aria-controls="siswa-center" role="tab" aria-selected="false">Siswa</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="guru-tab-center" data-bs-toggle="tab" href="#guru-center"
                            aria-controls="guru-center" role="tab" aria-selected="true">Guru</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="databarang-tab-center" data-bs-toggle="tab" href="#databarang-center"
                            aria-controls="databarang-center" role="tab" aria-selected="false">Data Barang</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="databarangtetap-tab-center" data-bs-toggle="tab" href="#databarangtetap-center"
                            aria-controls="databarangtetap-center" role="tab" aria-selected="true">Data Barang Tetap</a>
                    </li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active" id="siswa-center" aria-labelledby="siswa-tab-center" role="tabpanel">
                        <div class="card-body">
                            <div class="table-responsive">
                            <table id="peminjamantabel" class="table table-bordered table-striped table-hover">
                                <thead>
                                    <tr>
                                        <th>No.</th>
                                        <th>Nama Siswa</th>
                                        <th>Barang</th>
                                        <th>Keterangan</th>
                                        <th>Waktu Peminjaman</th>
                                        <th>Waktu Pengembalian</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($peminjamansiswa as $data)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $data->nama_siswa }}</td>
                                        <td>{{ $data->nomor }} - {{ $data->nama_barang }}</td>
                                        <td class="text-capitalize">{{ $data->keterangan }}</td>
                                        <td>{{ $data->created_at }}</td>
                                        <td> @if ($data->keterangan === 'Barang sudah dikembalikan')
                                            {{ $data->updated_at }}
                                            @endif</td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        </div>
                    </div>
                    <div class="tab-pane" id="guru-center" aria-labelledby="guru-tab-center" role="tabpanel">
                        <div class="card-body">
                            <div class="table-responsive">
                            <table id="peminjamantabel" class="table table-bordered table-striped table-hover">
                                <thead>
                                    <tr>
                                        <th>No.</th>
                                        <th>Nama Guru</th>
                                        <th>Barang</th>
                                        <th>Keterangan</th>
                                        <th>Waktu Peminjaman</th>
                                        <th>Waktu Pengembalian</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($peminjamanguru as $data)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $data->nama_guru }}</td>
                                        <td>{{ $data->nomor }} - {{ $data->nama_barang }}</td>
                                        <td class="text-capitalize ">{{ $data->keterangan }}</td>
                                        <td>{{ $data->created_at }}</td>
                                        <td> @if ($data->keterangan === 'Barang sudah dikembalikan')
                                            {{ $data->updated_at }}
                                            @endif</td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane" id="databarang-center" aria-labelledby="databarang-tab-center" role="tabpanel">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">
                                    <div class="flex">
                                        <div>
                                        </div>
                                        <div>
                                            <div class="flex items-center">
                                                <form class="flex items-center" action="{{ route('admin.barang.print')}}" method="get">
                                                    <div><select id="kondisi" name="kondisi" class="select2bs4 form-control" required>
                                                        <option value="semua" selected>Semua</option>
                                                        <option value="baik">Baik</option>
                                                        <option value="rusak ringan">Rusak Ringan</option>
                                                        <option value="rusak berat">Rusak Berat</option>
                                                    </select></div>
                                                    <div>
                                                        <input type="submit" value="Download PDF" class="btn btn-warning ml-1">
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                
                                    </div>
                
                
                                </h3>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <table id="barangtable" class="table table-striped table-hover table-primary">
                                    <thead>
                                        <tr>
                                            <th>No.</th>
                                            <th>Nomor Barang</th>
                                            <th>Nama</th>
                                            <th>Merk</th>
                                            <th>Tahun</th>
                                            <th>Kondisi</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($barang as $data)
                                        <tr>
                                            <td>{{ $loop->iteration }}</td>
                                            <td>{{ $data->nomor }}</td>
                                            <td>{{ $data->nama }}</td>
                                            <td>{{ $data->merk }}</td>
                                            <td>{{ $data->tahun }}</td>
                                            <td>{{ $data->kondisi }}</td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane" id="databarangtetap-center" aria-labelledby="databarangtetap-tab-center" role="tabpanel">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">
                                    <div class="flex">
                                        <div>
                                        </div>
                                        <div>
                                            <div class="flex items-center">
                                                <form class="flex items-center" action="{{ route('admin.barangtetap.print')}}" method="get">
                                                    <div><select id="kondisi" name="kondisi" class="select2bs4 form-control" required>
                                                        <option value="semua" selected>Semua</option>
                                                        <option value="baik">Baik</option>
                                                        <option value="rusak ringan">Rusak Ringan</option>
                                                        <option value="rusak berat">Rusak Berat</option>
                                                    </select></div>
                                                    <div>
                                                        <input type="submit" value="Download PDF" class="btn btn-warning ml-1">
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                
                                    </div>
                                </h3>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <table id="barangtable" class="table table-striped table-hover table-primary">
                                    <thead>
                                        <tr>
                                            <th>No.</th>
                                            <th>Nomor Barang</th>
                                            <th>Nama</th>
                                            <th>Merk</th>
                                            <th>Tahun</th>
                                            <th>Lokasi</th>
                                            <th>Kondisi</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($barangtetap as $data)
                                          <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $data->nomor }}</td>
                                        <td>{{ $data->nama }}</td>
                                        <td>{{ $data->merk }}</td>
                                        <td>{{ $data->tahun }}</td>
                                        <td>{{ $data->lokasi }}</td>
                                        <td>{{ $data->kondisi }}</td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</x-user-layout>